[options]
HoldPkg = pacman glibc
Architecture = auto

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

[custom]
Server = http://custom.mirror1.com/$repo/os/$arch
Server = http://custom.mirror2.com/$repo/os/$arch
