# BikerOS .bashrc - Custom shell for bikers

# Set the prompt for a clean, professional look
PS1='\[\e[1;38;5;208m\]BikerOS\[\e[0m\] \[\e[1;34m\]\w\[\e[0m\] \$ '

# Aliases for common biker-related tasks
alias update='sudo pacman -Syu'
alias build-iso='sudo /home/builder/Biker-OS/scripts/build.sh'
alias clean='rm -rf /tmp/archiso-tmp'
alias ll='ls -lah'
alias grep='grep --color=auto'

# Export important paths
export PATH=$PATH:/home/builder/Biker-OS/scripts

# BikerOS Welcome Message
echo -e "\e[1;38;5;208mWelcome to BikerOS! Ride safe and keep your system up to date.\e[0m"
echo -e "\e[1;34mType 'update' to check for updates or 'build-iso' to build a new ISO.\e[0m"
